update biz_data_query_model_help_menu set menu_name_en = 'Syntax basis' where id=1;
update biz_data_query_model_help_menu set menu_name_en = 'Data export' where id=2;
update biz_data_query_model_help_menu set menu_name_en = 'ClickHouse functions' where id=3;
update biz_data_query_model_help_menu set menu_name_en = 'STAEMENTS' where id=5;
update biz_data_query_model_help_menu set menu_name_en = 'FUNCTION' where id=6;
update biz_data_query_model_help_menu set menu_name_en = 'AGGREGATE FUNCRTIONS' where id=7;
update biz_data_query_model_help_menu set menu_name_en = 'SELECT' where id=8;
update biz_data_query_model_help_menu set menu_name_en = 'ALTER' where id=10;
update biz_data_query_model_help_menu set menu_name_en = 'SYSTEM' where id=11;
update biz_data_query_model_help_menu set menu_name_en = 'SHOW' where id=12;
update biz_data_query_model_help_menu set menu_name_en = 'GRANK' where id=13;
update biz_data_query_model_help_menu set menu_name_en = 'REVOKE' where id=14;
update biz_data_query_model_help_menu set menu_name_en = 'OTHER' where id=15;
update biz_data_query_model_help_menu set menu_name_en = 'CREATE DATABASE' where id=16;
update biz_data_query_model_help_menu set menu_name_en = 'INSERT INTO' where id=17;
update biz_data_query_model_help_menu set menu_name_en = 'INTRODUCTION' where id=18;
update biz_data_query_model_help_menu set menu_name_en = 'Arithmetic Functions' where id=19;
update biz_data_query_model_help_menu set menu_name_en = 'Comparison Functions' where id=20;
update biz_data_query_model_help_menu set menu_name_en = 'Logical Functions' where id=21;
update biz_data_query_model_help_menu set menu_name_en = 'Type Conversion Functions' where id=22;
update biz_data_query_model_help_menu set menu_name_en = 'IN Operator' where id=23;
update biz_data_query_model_help_menu set menu_name_en = 'Introspection Functions' where id=24;
update biz_data_query_model_help_menu set menu_name_en = 'GEO Functions' where id=25;
update biz_data_query_model_help_menu set menu_name_en = 'Hash Functions' where id=26;
update biz_data_query_model_help_menu set menu_name_en = 'IP Functions' where id=27;
update biz_data_query_model_help_menu set menu_name_en = 'JSON Functions' where id=28;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Working with Nullable' where id=29;
update biz_data_query_model_help_menu set menu_name_en = 'URL Functions' where id=30;
update biz_data_query_model_help_menu set menu_name_en = 'UUID Functions' where id=31;
update biz_data_query_model_help_menu set menu_name_en = 'arrayJoin Functions' where id=32;
update biz_data_query_model_help_menu set menu_name_en = 'Bit Functions' where id=33;
update biz_data_query_model_help_menu set menu_name_en = 'Bitmap Functions' where id=34;
update biz_data_query_model_help_menu set menu_name_en = 'Other Functions' where id=35;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Working with Yandex.Metrica Dictionaries' where id=36;
update biz_data_query_model_help_menu set menu_name_en = 'Rounding Functions' where id=37;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Working with External Dictionaries' where id=38;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Working with Strings' where id=39;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Splitting and Merging Strings and Arrays' where id=40;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Searching in Strings' where id=41;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Searching and Replacing in Strings' where id=42;
update biz_data_query_model_help_menu set menu_name_en = 'Mathematical Functions' where id=43;
update biz_data_query_model_help_menu set menu_name_en = 'Array Functions' where id=44;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Working with Dates and Times' where id=45;
update biz_data_query_model_help_menu set menu_name_en = 'Machine Learning Functions' where id=46;
update biz_data_query_model_help_menu set menu_name_en = 'Conditional Functions' where id=47;
update biz_data_query_model_help_menu set menu_name_en = 'Encoding Functions' where id=48;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Generating Pseudo-Random Numbers' where id=49;
update biz_data_query_model_help_menu set menu_name_en = 'Higher-order functions' where id=50;
update biz_data_query_model_help_menu set menu_name_en = 'Functions for Generating Pseudo-Random Numbers' where id=51;
update biz_data_query_model_help_menu set menu_name_en = 'Reference' where id=52;
update biz_data_query_model_help_menu set menu_name_en = 'Aggregate Function Combinators' where id=53;
update biz_data_query_model_help_menu set menu_name_en = 'Parametric Aggregate Functions' where id=54;
update biz_data_query_model_help_menu set menu_name_en = 'Overview' where id=55;
update biz_data_query_model_help_menu set menu_name_en = 'ALL clause' where id=56;
update biz_data_query_model_help_menu set menu_name_en = 'ARRAY JOIN' where id=57;
update biz_data_query_model_help_menu set menu_name_en = 'DISTINCT' where id=58;
update biz_data_query_model_help_menu set menu_name_en = 'FORMAT' where id=59;
update biz_data_query_model_help_menu set menu_name_en = 'FROM ' where id=60;
update biz_data_query_model_help_menu set menu_name_en = 'GROUP BY' where id=61;
update biz_data_query_model_help_menu set menu_name_en = 'HAVING' where id=62;
update biz_data_query_model_help_menu set menu_name_en = 'INTO OUTFILE' where id=63;
update biz_data_query_model_help_menu set menu_name_en = 'JOIN' where id=64;
update biz_data_query_model_help_menu set menu_name_en = 'LIMIT' where id=65;
update biz_data_query_model_help_menu set menu_name_en = 'LIMIT BY' where id=66;
update biz_data_query_model_help_menu set menu_name_en = 'ORDER BY' where id=67;
update biz_data_query_model_help_menu set menu_name_en = 'PREWHERE' where id=68;
update biz_data_query_model_help_menu set menu_name_en = 'SAMPLE' where id=69;
update biz_data_query_model_help_menu set menu_name_en = 'UNION ALL' where id=70;
update biz_data_query_model_help_menu set menu_name_en = 'WHERE' where id=71;
update biz_data_query_model_help_menu set menu_name_en = 'WITH' where id=72;
update biz_data_query_model_help_menu set menu_name_en = 'count' where id=73;
update biz_data_query_model_help_menu set menu_name_en = 'min' where id=74;
update biz_data_query_model_help_menu set menu_name_en = 'max' where id=75;
update biz_data_query_model_help_menu set menu_name_en = 'sum' where id=76;
update biz_data_query_model_help_menu set menu_name_en = 'avg' where id=77;
update biz_data_query_model_help_menu set menu_name_en = 'any' where id=78;
update biz_data_query_model_help_menu set menu_name_en = 'stddevPop' where id=79;
update biz_data_query_model_help_menu set menu_name_en = 'stddevSamp' where id=80;
update biz_data_query_model_help_menu set menu_name_en = 'varPop(x)' where id=81;
update biz_data_query_model_help_menu set menu_name_en = 'varSamp' where id=82;
update biz_data_query_model_help_menu set menu_name_en = 'covarPop' where id=83;
update biz_data_query_model_help_menu set menu_name_en = 'covarSamp' where id=84;
update biz_data_query_model_help_menu set menu_name_en = 'anyHeavy' where id=85;
update biz_data_query_model_help_menu set menu_name_en = 'anyLast' where id=86;
update biz_data_query_model_help_menu set menu_name_en = 'argMin' where id=87;
update biz_data_query_model_help_menu set menu_name_en = 'argMax' where id=88;
update biz_data_query_model_help_menu set menu_name_en = 'avgWeighted' where id=89;
update biz_data_query_model_help_menu set menu_name_en = 'corr' where id=90;
update biz_data_query_model_help_menu set menu_name_en = 'topK' where id=91;
update biz_data_query_model_help_menu set menu_name_en = 'topKWeighted' where id=92;
update biz_data_query_model_help_menu set menu_name_en = 'groupArray' where id=93;
update biz_data_query_model_help_menu set menu_name_en = 'groupUniqArray' where id=94;
update biz_data_query_model_help_menu set menu_name_en = 'groupArrayInsertAt' where id=95;
update biz_data_query_model_help_menu set menu_name_en = 'groupArrayMovingSum' where id=96;
update biz_data_query_model_help_menu set menu_name_en = 'groupArrayMovingAvg' where id=97;
update biz_data_query_model_help_menu set menu_name_en = 'groupArraySample' where id=98;
update biz_data_query_model_help_menu set menu_name_en = 'groupBitAnd' where id=99;
update biz_data_query_model_help_menu set menu_name_en = 'groupBitOr' where id=100;
update biz_data_query_model_help_menu set menu_name_en = 'groupBitXor' where id=101;
update biz_data_query_model_help_menu set menu_name_en = 'groupBitmap' where id=102;
update biz_data_query_model_help_menu set menu_name_en = 'groupBitmapAnd' where id=103;
update biz_data_query_model_help_menu set menu_name_en = 'groupBitmapOr' where id=104;
update biz_data_query_model_help_menu set menu_name_en = 'groupBitmapXor' where id=105;
update biz_data_query_model_help_menu set menu_name_en = 'sumWithOverflow' where id=106;
update biz_data_query_model_help_menu set menu_name_en = 'deltaSum' where id=107;
update biz_data_query_model_help_menu set menu_name_en = 'sumMap' where id=108;
update biz_data_query_model_help_menu set menu_name_en = 'minMap' where id=109;
update biz_data_query_model_help_menu set menu_name_en = 'maxMap' where id=110;
update biz_data_query_model_help_menu set menu_name_en = 'initializeAggregation' where id=111;
update biz_data_query_model_help_menu set menu_name_en = 'skewPop' where id=112;
update biz_data_query_model_help_menu set menu_name_en = 'skewSamp' where id=113;
update biz_data_query_model_help_menu set menu_name_en = 'kurtPop' where id=114;
update biz_data_query_model_help_menu set menu_name_en = 'kurtSamp' where id=115;
update biz_data_query_model_help_menu set menu_name_en = 'uniq' where id=116;
update biz_data_query_model_help_menu set menu_name_en = 'uniqExact' where id=117;
update biz_data_query_model_help_menu set menu_name_en = 'uniqCombined' where id=118;
update biz_data_query_model_help_menu set menu_name_en = 'uniqCombined64' where id=119;
update biz_data_query_model_help_menu set menu_name_en = 'uniqHLL12' where id=120;
update biz_data_query_model_help_menu set menu_name_en = 'quantile' where id=121;
update biz_data_query_model_help_menu set menu_name_en = 'quantiles' where id=122;
update biz_data_query_model_help_menu set menu_name_en = 'quantileExact' where id=123;
update biz_data_query_model_help_menu set menu_name_en = 'quantileExactWeighted' where id=124;
update biz_data_query_model_help_menu set menu_name_en = 'quantileTiming' where id=125;
update biz_data_query_model_help_menu set menu_name_en = 'quantileTimingWeighted' where id=126;
update biz_data_query_model_help_menu set menu_name_en = 'quantileDeterministic' where id=127;
update biz_data_query_model_help_menu set menu_name_en = 'quantileTDigest' where id=128;
update biz_data_query_model_help_menu set menu_name_en = 'quantileTDigestWeighted' where id=129;
update biz_data_query_model_help_menu set menu_name_en = 'simpleLinearRegression' where id=130;
update biz_data_query_model_help_menu set menu_name_en = 'stochasticLinearRegression' where id=131;
update biz_data_query_model_help_menu set menu_name_en = 'stochasticLogisticRegression' where id=132;
update biz_data_query_model_help_menu set menu_name_en = 'categoricalInformationValue' where id=133;
update biz_data_query_model_help_menu set menu_name_en = 'studentTTest' where id=134;
update biz_data_query_model_help_menu set menu_name_en = 'welchTTest' where id=135;
update biz_data_query_model_help_menu set menu_name_en = 'mannWhitneyUTest' where id=136;
update biz_data_query_model_help_menu set menu_name_en = 'median' where id=137;
update biz_data_query_model_help_menu set menu_name_en = 'rankCorr' where id=138;
