spring:
  application:
    name: boot-05-web-admin
  datasource:
    url: jdbc:mysql://localhost:3306/ssmbuild
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

   # http://localhost:8080/druid/login.html  德鲁伊的界面
    druid:
      filters: stat,wall,slf4j   # stat:开启了web监控   wall:防火墙   slf4j:日志
      aop-patterns: com.dhao.admin.* # 监控SpringBean
      stat-view-servlet:             #配置监控页功能
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: flalse   # 重置按钮禁用掉

      web-stat-filter:  # 监控web应用的
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
      filter:
        stat:          #对上面的filters里面的stat的详细配置
          slow-sql-millis: 1000 #慢查询时间
          log-slow-sql: true #开启慢查询
          enabled: true
        wall:
          enabled: true
          config:
            drop-table-allow: false #所有的删表动作都不允许
  redis:
    database: 0
    host: 127.0.0.1 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password:   # Redis服务器连接密码（默认为空）
    timeout: 1000 # 连接超时时间（毫秒）
    jedis:
      pool:
        min-idle: 0 #  连接池中的最小空闲连接
        max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 100  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
  boot:
    admin:
      client:
        url: http://localhost:8888   # Spring Boot Admin Server 监控的地址
        instance:
          prefer-ip: true  # 用ip注册进去




mybatis:
  mapper-locations: classpath:mapper/**/*.xml
 # configuration:  # 指定mybatis 全局配置文件中的相关配置项
 #   map-underscore-to-camel-case: true  # 开启驼峰规则
logging:
  level:
    com.dhao.admin: debug
#    org.springframework: debug

# management 是所有actuator的配置
# management.endpoint.端点名.xxx  针对某一个端点的具体配置
management:
  endpoints:
    enabled-by-default: true #默认开启所有监控端点:true(会暴露所有端点信息)
    web:
      exposure:
        include: '*'  #以web方式暴露出来
  endpoint:
    health:
      show-components: always  # 健康状态总是显示
      enabled: true # 开启健康端点信息

    info:            # 应用程序信息
      enabled: true
    beans:          # 容器中的bean
      enabled: true
    metrics:          # 运行指标
      enabled: true
    loggers:         # 日志记录
      enabled: true
info:
  appName: boot-admin
  appVersion: 1.0.0
  mavenProjectName: @project.artifactId@ # pom文件中的项目名称
  mavenProjectVersion: @project.version@ #pom文件中的项目版本号









