#1.静态资源的存放类路径: called /static (or /public or /resources or /META-INF/resources
# 在上述这些路径下,都可以访问到静态资源
#2. 默认静态资源访问路径:/** ,  但是我们配上/res/** 的话访问路径上面需要加/res/...
#3. 我们可以自定义一个访问路径:  [classpath:/abc/] ,将静态资源放到这个文件中,访问路径仍为/res/...
#  这样才能访问的到静态资源
#
#spring:
#  mvc:
#    static-path-pattern: /res/**    # 设置静态资源的访问路径
#  resources:
#    static-locations: [classpath:/abc/]   # 设置静态资源存放的路径

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true   #开启页面表单的Rest功能, 微服务的话,postman 使用的话,都不用开启,只有和页面交互的话开启